#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "lists.h"

/**
 * main - check the code
 *
 * Return: Always EXIT_SUCCESS.
 */
int main(void)
{
	dlistint_t *head;

	head = NULL;
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -7676);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, -464);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 6876);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -34556);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -3453);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head,-53458);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -86875);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -134577);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, -983839);
	add_dnodeint_end(&head, -121051);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);



	insert_dnodeint_at_index(&head, 150, 10000);
	insert_dnodeint_at_index(&head, 0, 777);
	insert_dnodeint_at_index(&head, 20, 777);
	insert_dnodeint_at_index(&head, 30, 777);
	insert_dnodeint_at_index(&head, 40, 777);
	insert_dnodeint_at_index(&head, 50, 777);
	insert_dnodeint_at_index(&head, 60, 777);
	insert_dnodeint_at_index(&head, 70, 777);
	insert_dnodeint_at_index(&head, 80, 777);
	insert_dnodeint_at_index(&head, 90, 777);
	insert_dnodeint_at_index(&head, 10, 777);
	printf("->%ld elements\n", print_dlistint(head));

	printf("-----------------\n");

	free_dlistint(head);
	head = NULL;

	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -7676);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, -464);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 6876);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -34556);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -3453);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head,-53458);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -86875);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -134577);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -150);
	add_dnodeint_end(&head, -983839);
	add_dnodeint_end(&head, -121051);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, -98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);
	add_dnodeint_end(&head, 98);


	insert_dnodeint_at_index(&head, 150, 777);
	insert_dnodeint_at_index(&head, 0, 10000);
	insert_dnodeint_at_index(&head, 20, 777);
	insert_dnodeint_at_index(&head, 30, 777);
	insert_dnodeint_at_index(&head, 40, 777);
	insert_dnodeint_at_index(&head, 50, 777);
	insert_dnodeint_at_index(&head, 60, 777);
	insert_dnodeint_at_index(&head, 70, 777);
	insert_dnodeint_at_index(&head, 80, 777);
	insert_dnodeint_at_index(&head, 90, 777);
	insert_dnodeint_at_index(&head, 10, 777);
	printf("->%ld elements\n", print_dlistint(head));
	free_dlistint(head);
	head = NULL;
	return (EXIT_SUCCESS);
}
